#!/bin/bash

###########################################
# NAME:		avscr-timelapse
# AUTHOR:	balex
# LICENSE:	Creative Commons Attribution - Share Alike 3.0 http://creativecommons.org/licenses/by-sa/3.0/
#		You are free to use and/or modify this script. If you choose to distribute this script, with or
#		without changes, you must attribute credit to the author listed above.
# REQUIRES:	ffmpeg
# VERSION:	1.0
# DESCRIPTION:	A script to create a video timelapse based on all the photos from a directory.
#
###########################################

# Initialize variables
# TODO: implement getopts
echo "Usage avscr-timelapse <output file> <video rate fps>"

ffmpeg -f image2 -i %.JPG -r $2 -s hd1080 -vcodec libx264 $1
