#!/bin/bash

###########################################
# NAME:		avscr-watermark
# AUTHOR:	Linerd (http://tuxtweaks.com), Copyright 2009
#		balex
# LICENSE:	Creative Commons Attribution - Share Alike 3.0 http://creativecommons.org/licenses/by-sa/3.0/
#		You are free to use and/or modify this script. If you choose to distribute this script, with or
#		without changes, you must attribute credit to the author listed above.
# REQUIRES:	ImageMagick, coreutils
# VERSION:	1.0
# DESCRIPTION:	A script to add a watermark to all images in a directory.
#		Original images will be retained and new watermarked images will be created.
#
###########################################

# Initialize variables
# TODO: implement getopts
echo "Usage avscr-watermark <WM file path> <WM scale> <WM position: NorthWest, North, NorthEast, West, Center, East, SouthWest, South, SouthEast"

WM=$1		 # This is the path to your watermark image
SCALE=$2         # This sets the scale % of your watermark image

# Find all image files in current directory and watermark.
file -i * | grep image | awk -F':' '{ print $1 }' | while read IMAGE
        do
                echo Watermarking $IMAGE
                mkdir watermarked
                composite -dissolve 100% -gravity $3 -geometry +50+50 -quality 100 \( $WM -resize $SCALE% \) "$IMAGE" \
                        "watermarked/$IMAGE"
        done
exit 0
